version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: sittidop-postgres-dev
    restart: always
    environment:
      POSTGRES_USER: "sitti"
      POSTGRES_PASSWORD: "V@radorn7887"
      POSTGRES_DB: "sittidop"
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

volumes:
  postgres_dev_data:
    driver: local
