import {
  Role,
  BenefitCategory,
  PaymentFrequency,
  ApplicationStatus,
  ApprovalDecision,
  VulnerabilityLevel,
} from "../../core/domain/value-objects/enums";

export const initialBenefitPrograms = [
  {
    id: "dop-eld-001",
    code: "DOP-ELD-001",
    name: "เบี้ยยังชีพผู้สูงอายุ (Elderly Living Allowance)",
    thaiName: "เบี้ยยังชีพผู้สูงอายุแห่งชาติ",
    description: "เงินช่วยเหลือรายเดือนสำหรับผู้สูงอายุสัญชาติไทยที่มีอายุ 60 ปีขึ้นไป เพื่อการยังชีพตามเกณฑ์ขั้นบันได",
    category: BenefitCategory.LIVING_ALLOWANCE,
    targetGroup: "ผู้สูงอายุสัญชาติไทย อายุ 60 ปีขึ้นไป และมีชื่อในทะเบียนบ้าน",
    budgetTotal: 88500000000,
    budgetDisbursed: 64200000000,
    maxAmount: 1000,
    paymentFrequency: PaymentFrequency.MONTHLY,
    legalBasis: "พ.ร.บ. ผู้สูงอายุ พ.ศ. 2546 และระเบียบกระทรวงมหาดไทย พ.ศ. 2566",
    isActive: true,
  },
  {
    id: "dop-dis-002",
    code: "DOP-DIS-002",
    name: "เบี้ยความพิการสำหรับผู้สูงอายุ (Elderly Disability Benefit)",
    thaiName: "เบี้ยความพิการและเงินช่วยเหลือผู้พิการสูงวัย",
    description: "เงินสวัสดิการรายเดือนสำหรับคนพิการที่มีบัตรประจำตัวคนพิการถูกต้องตามกฎหมาย และเงินเพิ่มพิเศษกรณีมีบัตรสวัสดิการแห่งรัฐ",
    category: BenefitCategory.DISABILITY_BENEFIT,
    targetGroup: "คนพิการที่มีสมุด/บัตรประจำตัวคนพิการ อายุ 18 ปีขึ้นไป",
    budgetTotal: 24000000000,
    budgetDisbursed: 18500000000,
    maxAmount: 1000,
    paymentFrequency: PaymentFrequency.MONTHLY,
    legalBasis: "พ.ร.บ. ส่งเสริมและพัฒนาคุณภาพชีวิตคนพิการ พ.ศ. 2550",
    isActive: true,
  },
  {
    id: "dop-swc-003",
    code: "DOP-SWC-003",
    name: "สิทธิสวัสดิการแห่งรัฐเสริมสำหรับผู้สูงอายุ (State Welfare Card)",
    thaiName: "สวัสดิการแห่งรัฐสำหรับผู้สูงอายุรายได้น้อย",
    description: "วงเงินซื้อสินค้าอุปโภคบริโภค ส่วนลดค่าสาธารณูปโภค และเงินสงเคราะห์พิเศษผู้สูงอายุรายได้น้อย",
    category: BenefitCategory.STATE_WELFARE_TOPUP,
    targetGroup: "ผู้สูงอายุที่ผ่านเกณฑ์การลงทะเบียนเพื่อสวัสดิการแห่งรัฐ",
    budgetTotal: 45000000000,
    budgetDisbursed: 38200000000,
    maxAmount: 1415,
    paymentFrequency: PaymentFrequency.MONTHLY,
    legalBasis: "มติคณะรัฐมนตรี มาตรการช่วยเหลือผ่านบัตรสวัสดิการแห่งรัฐ",
    isActive: true,
  },
  {
    id: "dop-emg-004",
    code: "DOP-EMG-004",
    name: "เงินสงเคราะห์ผู้สูงอายุในภาวะยากลำบาก (Emergency Hardship Assistance)",
    thaiName: "เงินสงเคราะห์และคุ้มครองสิทธิผู้สูงอายุที่ประสบปัญหาความเดือดร้อน",
    description: "เงินช่วยเหลือฉุกเฉินสำหรับผู้สูงอายุที่ประสบปัญหาความเดือดร้อน ไร้ที่พึ่ง หรือขาดผู้อุปการะ วงเงินสูงสุด 3,000 บาท/ครั้ง ไม่เกิน 3 ครั้ง/ปี",
    category: BenefitCategory.EMERGENCY_GRANT,
    targetGroup: "ผู้สูงอายุอายุ 60 ปีขึ้นไปที่ยากไร้ ตกทุกข์ได้ยาก หรือถูกทอดทิ้ง",
    budgetTotal: 1500000000,
    budgetDisbursed: 920000000,
    maxAmount: 3000,
    paymentFrequency: PaymentFrequency.PER_OCCURRENCE,
    legalBasis: "ระเบียบกรมกิจการผู้สูงอายุ พ.ศ. 2560",
    isActive: true,
  },
  {
    id: "dop-hsg-005",
    code: "DOP-HSG-005",
    name: "เงินช่วยเหลือปรับปรุงสภาพแวดล้อมที่อยู่อาศัยผู้สูงอายุ (Home Renovation Grant)",
    thaiName: "โครงการปรับปรุงบ้านและสิ่งอำนวยความสะดวกสำหรับผู้สูงอายุ",
    description: "เงินสนับสนุนปรับปรุงห้องน้ำ ทางลาด ประตู หลังคา และโครงสร้างบ้านให้ปลอดภัยและเอื้อต่อสุขอนามัยของผู้สูงอายุ",
    category: BenefitCategory.HOUSING_RENOVATION,
    targetGroup: "ผู้สูงอายุที่มีบ้านพักอาศัยชำรุดทรุดโทรม ไม่ปลอดภัย และมีฐานะยากจน",
    budgetTotal: 3200000000,
    budgetDisbursed: 2100000000,
    maxAmount: 40000,
    paymentFrequency: PaymentFrequency.ONE_TIME,
    legalBasis: "ระเบียบกรมกิจการผู้สูงอายุว่าด้วยการปรับปรุงสภาพแวดล้อมที่อยู่อาศัย",
    isActive: true,
  },
  {
    id: "dop-fnl-006",
    code: "DOP-FNL-006",
    name: "เงินสงเคราะห์ในการจัดการศพผู้สูงอายุตามประเพณี (Funeral Assistance)",
    thaiName: "เงินสงเคราะห์ค่าทำศพผู้สูงอายุตามประเพณี",
    description: "เงินช่วยเหลือแก่ครอบครัวหรือผู้จัดการศพผู้สูงอายุตามประเพณี รายละ 3,000 บาท",
    category: BenefitCategory.FUNERAL_AID,
    targetGroup: "ทายาทหรือผู้จัดการศพผู้สูงอายุสัญชาติไทยที่มีฐานะยากจน/ถือบัตรสวัสดิการแห่งรัฐ",
    budgetTotal: 2800000000,
    budgetDisbursed: 2350000000,
    maxAmount: 3000,
    paymentFrequency: PaymentFrequency.PER_OCCURRENCE,
    legalBasis: "ประกาศกระทรวงการพัฒนาสังคมและความมั่นคงของมนุษย์ พ.ศ. 2557",
    isActive: true,
  },
  {
    id: "dop-loan-007",
    code: "DOP-LOAN-007",
    name: "เงินทุนกู้ยืมเพื่อการประกอบอาชีพสำหรับผู้สูงอายุ (Occupational Revolving Loan)",
    thaiName: "กองทุนผู้สูงอายุเพื่อการกู้ยืมประกอบอาชีพ ปลอดดอกเบี้ย (0%)",
    description: "เงินกู้ยืมปลอดดอกเบี้ยเพื่อประกอบอาชีพ รายบุคคลสูงสุด 30,000 บาท รายกลุ่มสูงสุด 100,000 บาท ผ่อนชำระ 3 ปี",
    category: BenefitCategory.OCCUPATIONAL_LOAN,
    targetGroup: "ผู้สูงอายุ 60-75 ปีที่มีศักยภาพและแผนการประกอบอาชีพชัดเจน",
    budgetTotal: 5000000000,
    budgetDisbursed: 3800000000,
    maxAmount: 30000,
    paymentFrequency: PaymentFrequency.ONE_TIME,
    legalBasis: "ระเบียบคณะกรรมการกองทุนผู้สูงอายุ พ.ศ. 2547",
    isActive: true,
  },
];

export const initialCitizens = [
  {
    id: "cit-001",
    nationalId: "1100400289112",
    title: "นาย",
    firstName: "สมศักดิ์",
    lastName: "มั่นคง",
    dateOfBirth: new Date("1954-04-12"), // Age ~72
    gender: "MALE",
    phone: "081-456-7890",
    email: "somsak.m@gmail.com",
    address: "124/5 หมู่ 3 ซอยสุขเกษม ถนนประชาชื่น",
    subdistrict: "วงศ์สว่าง",
    district: "บางซื่อ",
    province: "กรุงเทพมหานคร",
    postalCode: "10800",
    monthlyIncome: 2500,
    hasStateWelfareCard: true,
    isDisabilityRegistered: false,
    disabilityType: null,
    vulnerabilityScore: 55,
    vulnerabilityLevel: VulnerabilityLevel.HIGH,
    livingCondition: "ALONE",
  },
  {
    id: "cit-002",
    nationalId: "3500100456123",
    title: "นาง",
    firstName: "สมใจ",
    lastName: "เจริญสุข",
    dateOfBirth: new Date("1942-08-25"), // Age ~84
    gender: "FEMALE",
    phone: "089-123-4567",
    email: null,
    address: "88/1 หมู่ 5 ตำบลสุเทพ",
    subdistrict: "สุเทพ",
    district: "เมืองเชียงใหม่",
    province: "เชียงใหม่",
    postalCode: "50200",
    monthlyIncome: 0,
    hasStateWelfareCard: true,
    isDisabilityRegistered: true,
    disabilityType: "ทางการเคลื่อนไหว (ข้อเข่าเสื่อมรุนแรง)",
    vulnerabilityScore: 85,
    vulnerabilityLevel: VulnerabilityLevel.CRITICAL,
    livingCondition: "BEDRIDDEN",
  },
  {
    id: "cit-003",
    nationalId: "3400200112345",
    title: "นาย",
    firstName: "บุญมี",
    lastName: "มีลาภ",
    dateOfBirth: new Date("1961-11-03"), // Age ~64
    gender: "MALE",
    phone: "086-778-9901",
    email: null,
    address: "45 หมู่ 2 บ้านหนองหญ้าปล้อง",
    subdistrict: "ในเมือง",
    district: "เมืองขอนแก่น",
    province: "ขอนแก่น",
    postalCode: "40000",
    monthlyIncome: 4500,
    hasStateWelfareCard: true,
    isDisabilityRegistered: false,
    disabilityType: null,
    vulnerabilityScore: 35,
    vulnerabilityLevel: VulnerabilityLevel.MODERATE,
    livingCondition: "FAMILY",
  },
  {
    id: "cit-004",
    nationalId: "1900300998877",
    title: "นางสาว",
    firstName: "ประภา",
    lastName: "แสงสุวรรณ",
    dateOfBirth: new Date("1933-02-14"), // Age ~93
    gender: "FEMALE",
    phone: "084-555-1234",
    email: null,
    address: "9/12 ถนนบรมไตรโลกนารถ",
    subdistrict: "ในเมือง",
    district: "เมืองพิษณุโลก",
    province: "พิษณุโลก",
    postalCode: "65000",
    monthlyIncome: 0,
    hasStateWelfareCard: true,
    isDisabilityRegistered: false,
    disabilityType: null,
    vulnerabilityScore: 75,
    vulnerabilityLevel: VulnerabilityLevel.CRITICAL,
    livingCondition: "ALONE",
  },
  {
    id: "cit-005",
    nationalId: "1300900776655",
    title: "นาย",
    firstName: "อำนวย",
    lastName: "พงษ์พานิช",
    dateOfBirth: new Date("1958-06-19"), // Age ~68
    gender: "MALE",
    phone: "082-334-5566",
    email: "amnuay.p@outlook.com",
    address: "223 หมู่ 4 ตำบลเกาะยอ",
    subdistrict: "เกาะยอ",
    district: "เมืองสงขลา",
    province: "สงขลา",
    postalCode: "90100",
    monthlyIncome: 6500,
    hasStateWelfareCard: false,
    isDisabilityRegistered: true,
    disabilityType: "ทางการได้ยิน (หูตึงปานกลาง)",
    vulnerabilityScore: 40,
    vulnerabilityLevel: VulnerabilityLevel.MODERATE,
    livingCondition: "FAMILY",
  },
  {
    id: "cit-006",
    nationalId: "1400800332211",
    title: "นาง",
    firstName: "มาลี",
    lastName: "ศรีอุบล",
    dateOfBirth: new Date("1950-09-08"), // Age ~75
    gender: "FEMALE",
    phone: "085-667-8899",
    email: null,
    address: "105 หมู่ 7 บ้านดอนกลาง",
    subdistrict: "ขามใหญ่",
    district: "เมืองอุบลราชธานี",
    province: "อุบลราชธานี",
    postalCode: "34000",
    monthlyIncome: 1200,
    hasStateWelfareCard: true,
    isDisabilityRegistered: false,
    disabilityType: null,
    vulnerabilityScore: 60,
    vulnerabilityLevel: VulnerabilityLevel.HIGH,
    livingCondition: "ALONE",
  },
  {
    id: "cit-007",
    nationalId: "1200600445566",
    title: "นาย",
    firstName: "ประสิทธิ์",
    lastName: "บุญส่งเสริม",
    dateOfBirth: new Date("1963-03-22"), // Age ~63
    gender: "MALE",
    phone: "083-998-1122",
    email: "prasit.bs@gmail.com",
    address: "51/4 หมู่ 1 ตำบลหนองปรือ",
    subdistrict: "หนองปรือ",
    district: "บางละมุง",
    province: "ชลบุรี",
    postalCode: "20150",
    monthlyIncome: 8500,
    hasStateWelfareCard: false,
    isDisabilityRegistered: false,
    disabilityType: null,
    vulnerabilityScore: 20,
    vulnerabilityLevel: VulnerabilityLevel.LOW,
    livingCondition: "FAMILY",
  },
  {
    id: "cit-008",
    nationalId: "3300500889900",
    title: "นาง",
    firstName: "ทองดี",
    lastName: "โคราช",
    dateOfBirth: new Date("1947-12-01"), // Age ~78
    gender: "FEMALE",
    phone: "087-445-6677",
    email: null,
    address: "77 หมู่ 11 ตำบลจอหอ",
    subdistrict: "จอหอ",
    district: "เมืองนครราชสีมา",
    province: "นครราชสีมา",
    postalCode: "30310",
    monthlyIncome: 1500,
    hasStateWelfareCard: true,
    isDisabilityRegistered: true,
    disabilityType: "ทางการมองเห็น (ต้อกระจกข้างขวา)",
    vulnerabilityScore: 70,
    vulnerabilityLevel: VulnerabilityLevel.HIGH,
    livingCondition: "FAMILY",
  },
];

export const initialApplications = [
  {
    id: "app-001",
    applicationNumber: "APP-2569-0001",
    citizenId: "cit-002",
    programId: "dop-hsg-005",
    requestedAmount: 40000,
    approvedAmount: 40000,
    status: ApplicationStatus.APPROVED,
    submissionDate: new Date("2026-08-05T09:30:00Z"),
    decisionDate: new Date("2026-08-10T14:15:00Z"),
    disbursementDate: new Date("2026-08-18T10:00:00Z"),
    documentsJson: JSON.stringify([
      { name: "สำเนาบัตรประชาชน_นางสมใจ.pdf", verified: true },
      { name: "หนังสือยินยอมปรับปรุงบ้าน.pdf", verified: true },
      { name: "ภาพถ่ายสภาพบันไดและห้องน้ำเดิม.jpg", verified: true },
      { name: "ใบเสนอราคาค่าวัสดุปรับปรุงทางลาด.pdf", verified: true },
    ]),
    officerNotes: "ผ่านการตรวจสอบข้อเท็จจริงในพื้นที่โดย อพม. แล้ว สภาพบ้านทรุดโทรมและผู้สูงอายุติดเตียง จำเป็นต้องทำทางลาดและห้องน้ำคนพิการเร่งด่วน อนุมัติเต็มวงเงิน 40,000 บาท",
    applicantRemarks: "ขอความอนุเคราะห์ปรับปรุงห้องน้ำและทางลาดเพื่อความปลอดภัยในการเคลื่อนย้าย",
  },
  {
    id: "app-002",
    applicationNumber: "APP-2569-0002",
    citizenId: "cit-001",
    programId: "dop-emg-004",
    requestedAmount: 3000,
    approvedAmount: 3000,
    status: ApplicationStatus.DISBURSED,
    submissionDate: new Date("2026-08-08T10:20:00Z"),
    decisionDate: new Date("2026-08-12T11:00:00Z"),
    disbursementDate: new Date("2026-08-15T15:30:00Z"),
    documentsJson: JSON.stringify([
      { name: "สำเนาบัตรประชาชน_สมศักดิ์.pdf", verified: true },
      { name: "แบบสอบประวัติความเดือดร้อน.pdf", verified: true },
      { name: "หนังสือรับรองจากประธานชุมชน.pdf", verified: true },
    ]),
    officerNotes: "ผู้สูงอายุอยู่คนเดียว ไม่มีรายได้ประจำ ผ่านเกณฑ์สงเคราะห์ฉุกเฉิน โอนเงินเข้าบัญชีพร้อมเพย์เรียบร้อย",
    applicantRemarks: "ขอรับเงินช่วยเหลือฉุกเฉินเนื่องจากมีค่าใช้จ่ายยาและค่าครองชีพ",
  },
  {
    id: "app-003",
    applicationNumber: "APP-2569-0003",
    citizenId: "cit-004",
    programId: "dop-emg-004",
    requestedAmount: 3000,
    approvedAmount: null,
    status: ApplicationStatus.UNDER_REVIEW,
    submissionDate: new Date("2026-08-16T13:45:00Z"),
    decisionDate: null,
    disbursementDate: null,
    documentsJson: JSON.stringify([
      { name: "สำเนาบัตรประชาชน_นางสาวประภา.pdf", verified: true },
      { name: "แบบบันทึกการเยี่ยมบ้าน.pdf", verified: false },
    ]),
    officerNotes: "รอผลการยืนยันการเยี่ยมบ้านเพิ่มเติมจาก พมจ.พิษณุโลก",
    applicantRemarks: "อายุ 93 ปี อยู่คนเดียว สุขภาพอ่อนแอ",
  },
  {
    id: "app-004",
    applicationNumber: "APP-2569-0004",
    citizenId: "cit-003",
    programId: "dop-loan-007",
    requestedAmount: 30000,
    approvedAmount: null,
    status: ApplicationStatus.DOCUMENT_VERIFIED,
    submissionDate: new Date("2026-08-17T11:15:00Z"),
    decisionDate: null,
    disbursementDate: null,
    documentsJson: JSON.stringify([
      { name: "สำเนาบัตรประชาชน_บุญมี.pdf", verified: true },
      { name: "โครงการปลูกพืชผักไฮโดรโปนิกส์.pdf", verified: true },
      { name: "เอกสารผู้ค้ำประกัน.pdf", verified: true },
    ]),
    officerNotes: "เอกสารครบถ้วน รอการประชุมคณะอนุกรรมการพิจารณาเงินกู้กองทุนผู้สูงอายุประจำเดือน",
    applicantRemarks: "ขอกู้เงินทุนหมุนเวียนเพื่อลงทุนปลูกผักจำหน่ายในตลาดชุมชน",
  },
  {
    id: "app-005",
    applicationNumber: "APP-2569-0005",
    citizenId: "cit-006",
    programId: "dop-hsg-005",
    requestedAmount: 22500,
    approvedAmount: null,
    status: ApplicationStatus.SUBMITTED,
    submissionDate: new Date("2026-08-19T08:30:00Z"),
    decisionDate: null,
    disbursementDate: null,
    documentsJson: JSON.stringify([
      { name: "บัตรประชาชน_นางมาลี.pdf", verified: false },
      { name: "ภาพถ่ายหลังคาบ้านชำรุด.jpg", verified: false },
    ]),
    officerNotes: "คำขอใหม่ อยู่ในคิวรอเจ้าหน้าที่รับเรื่องและตรวจสอบเอกสารเบื้องต้น",
    applicantRemarks: "หลังคาบ้านรั่วหลายจุด เวลาฝนตกน้ำท่วมขังพื้นบ้าน",
  },
  {
    id: "app-006",
    applicationNumber: "APP-2569-0006",
    citizenId: "cit-008",
    programId: "dop-dis-002",
    requestedAmount: 1000,
    approvedAmount: 1000,
    status: ApplicationStatus.APPROVED,
    submissionDate: new Date("2026-08-14T14:00:00Z"),
    decisionDate: new Date("2026-08-18T16:20:00Z"),
    disbursementDate: null,
    documentsJson: JSON.stringify([
      { name: "สำเนาบัตรคนพิการ_ทองดี.pdf", verified: true },
      { name: "หน้าสมุดบัญชีธนาคาร.pdf", verified: true },
    ]),
    officerNotes: "อนุมัติรับเบี้ยความพิการเพิ่มตามสิทธิ 1,000 บาท/เดือน (รวมเงินเพิ่มบัตรสวัสดิการแห่งรัฐ) ส่งต่อกรมบัญชีกลางจัดรอบจ่าย",
    applicantRemarks: "ยื่นขอรับเงินเพิ่มเบี้ยความพิการผ่านระบบอิเล็กทรอนิกส์",
  },
  {
    id: "app-007",
    applicationNumber: "APP-2569-0007",
    citizenId: "cit-005",
    programId: "dop-loan-007",
    requestedAmount: 30000,
    approvedAmount: null,
    status: ApplicationStatus.SUBMITTED,
    submissionDate: new Date("2026-08-20T09:10:00Z"),
    decisionDate: null,
    disbursementDate: null,
    documentsJson: JSON.stringify([
      { name: "บัตรประชาชน_อำนวย.pdf", verified: false },
      { name: "แผนงานแปรรูปอาหารทะเล.pdf", verified: false },
    ]),
    officerNotes: "รอนัดสัมภาษณ์แผนการดำเนินงาน",
    applicantRemarks: "ขอรับทุนกู้ยืมทำผลิตภัณฑ์แปรรูปสัตว์น้ำเกาะยอ",
  },
];

export const initialAuditLogs = [
  {
    id: "aud-001",
    userId: "usr-superadmin",
    userName: "พลเอก ภูมิพัฒน์ ภักดีชนม์",
    role: "SUPERADMIN",
    action: "LOGIN",
    resource: "Auth",
    resourceId: "usr-superadmin",
    detailsJson: JSON.stringify({ email: "superadmin@mod.go.th", role: "SUPERADMIN", method: "Credentials / MFA", status: "SUCCESS" }),
    ipAddress: "192.168.10.101",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/126.0.0.0",
    timestamp: new Date("2026-08-21T07:00:00Z"),
  },
  {
    id: "aud-002",
    userId: "usr-staff",
    userName: "พันตรี นพดล สายสวัสดิการ",
    role: "STAFF",
    action: "CREATE",
    resource: "MilitaryPersonnel",
    resourceId: "4920194821",
    detailsJson: JSON.stringify({
      militaryId: "4920194821",
      rank: "ร้อยเอก",
      name: "ภาคิน รักษ์ชาติ",
      unit: "ร.31 พัน.1 รอ.",
      lossType: "เสียชีวิตในการปฏิบัติหน้าที่ราชการสนาม",
      salary: 32880,
    }),
    ipAddress: "192.168.10.145",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/126.0.0.0",
    timestamp: new Date("2026-08-21T07:15:00Z"),
  },
  {
    id: "aud-003",
    userId: "usr-admin",
    userName: "พันเอก พงศกร พิทักษ์สิทธิ์",
    role: "ADMIN",
    action: "UPDATE",
    resource: "BenefitRule",
    resourceId: "R-LUMP-001",
    detailsJson: JSON.stringify({
      ruleCode: "R-LUMP-001",
      ruleName: "บำเหน็จตกทอดทายาทกำลังพล",
      formulaExpression: "{promotedSalary} * {totalServiceYears}",
      multiplierFactor: 1,
      baseAmount: 0,
    }),
    ipAddress: "192.168.10.112",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/126.0.0.0",
    timestamp: new Date("2026-08-21T07:25:00Z"),
  },
  {
    id: "aud-004",
    userId: "usr-commander",
    userName: "พลโท สมโชค ชัยชนะ",
    role: "COMMANDER",
    action: "EXPORT_DOCX",
    resource: "OfficialDocument",
    resourceId: "4920194821",
    detailsJson: JSON.stringify({
      template: "BENEFIT_SUMMARY",
      format: "docx",
      personnelName: "ร.อ. ภาคิน รักษ์ชาติ",
      militaryId: "4920194821",
      fileName: "Benefit_Summary_4920194821.docx",
    }),
    ipAddress: "192.168.10.105",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/126.0.0.0",
    timestamp: new Date("2026-08-21T07:35:00Z"),
  },
  {
    id: "aud-005",
    userId: "usr-commander",
    userName: "พลโท สมโชค ชัยชนะ",
    role: "COMMANDER",
    action: "EXPORT_PDF",
    resource: "OfficialDocument",
    resourceId: "4920194821",
    detailsJson: JSON.stringify({
      template: "BENEFIT_CERTIFICATE",
      format: "pdf",
      personnelName: "ร.อ. ภาคิน รักษ์ชาติ",
      militaryId: "4920194821",
      withSignature: true,
      withQrCode: true,
    }),
    ipAddress: "192.168.10.105",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/126.0.0.0",
    timestamp: new Date("2026-08-21T07:40:00Z"),
  },
  {
    id: "aud-006",
    userId: "usr-admin",
    userName: "พันเอก พงศกร พิทักษ์สิทธิ์",
    role: "ADMIN",
    action: "DELETE",
    resource: "MilitaryPersonnel",
    resourceId: "temp-draft-009",
    detailsJson: JSON.stringify({ deletedReason: "รายการซ้ำซ้อนจากการนำเข้าข้อมูลทดสอบ", deletedBy: "admin@mod.go.th" }),
    ipAddress: "192.168.10.112",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/126.0.0.0",
    timestamp: new Date("2026-08-21T07:45:00Z"),
  },
];
